{% set name = "dotty-dict" %}
{% set version = "1.3.1" %}
{% set pypi_name = "dotty_dict" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 4b016e03b8ae265539757a53eba24b9bfda506fb94fbce0bee843c6f05541a15

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5,<4.0
    - poetry_core >=1.0.0
  run:
    - python >=3.5,<4.0

test:
  imports:
    - dotty_dict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dotty-dict/
  summary: Dictionary wrapper for quick access to deeply nested keys.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pawelzny/dotty_dict
  doc_url: https://dotty-dict.readthedocs.io

extra:
  recipe-maintainers:
    - KingDarBoja
    - thewchan
